### PR TITLE
removing the imports which fail with java 11

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Comment by berryma4** [comment]
This seems to be failing

**Comment by shroffk** [comment]
Failing on travis or on your local build.

Without this fix...none of the jersey modules are working with java 11

**Comment by shroffk** [comment]
```
[WARNING] Error injecting: org.eclipse.tycho.core.p2.P2ArtifactRepositoryLayout
java.lang.TypeNotPresentException: Type org.eclipse.tycho.core.p2.P2ArtifactRepositoryLayout not present
```

seems like a tycho thing. Not sure how this error maps to a change in the imports in the manifest that I removed.

**Comment by kasemir** [comment]
I can't seriously contribute here since all I have is a local product which now builds but then doesn't start (now comparing with the common product which does run).

Still, for the current state of things I think we can ignore travis errors as long as some local builds succeed.

**Comment by shroffk** [comment]
Ok...
So I undid the only change that was in the main pom... but tycho still fails.

I also re triggered the build on the master branch. Now that fails too.
Travis is pulling java 7 for some reason...maybe since java 8 has reached end of life???
```
$ java -Xmx32m -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
$ javac -J-Xmx32m -version
javac 1.7.0_80
install
0.00s$ echo 'Skipping mvn install'
before_script.1
0.00s$ chmod +x travis.sh
before_script.2
0.00s$ echo "MAVEN_OPTS='-Xmx2g -Xms1g'" > ~/.mavenrc
0.05s$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
The command "java -version" exited with 0.
```

**Comment by shroffk** [comment]
Ok...
Fixed it... travis file needed to be updated.
This should fix the currently failing master branch too...since it seems we are not on top of travis build files.

**Pull request merged**
