### PR TITLE
Batik bugfix

### PR DESCRIPTION
**Pull request by jbobnar**
Added one of the batik plugins to the thirdparty.

The original one is not packed correctly, because it is missing a dependency to one of the other plugins, which classes are used directly by the dom.svg plugin. The consequence is that the dom.svg cannot load the classes it needs. 

The added plugin should be offered on the thirdparty p2 repostiory, so that tycho will use it during build.

### CODE REVIEW

**Comment by jbobnar** [comment]
Investigating for a better solution, which doesn't require modification of the batik plugins.

**Comment by richardfearn** [comment]
That's good as all those class files being added to the repo looked a bit ugly :-|

**Comment by berryma4** [comment]
What's wrong, .. maybe I can help.  For thirdparty bundles, we are trying to use the maven-osgi-bundles repo (and slowly remove this repo).  The idea is, this repo is for sources that need to be touched, while the maven-osgi-bundles repo just bundles from maven "as is".

If you notice batik (line 96):
https://github.com/ControlSystemStudio/maven-osgi-bundles/blob/master/repository/pom.xml
it is just bundled from maven.

**Comment by jbobnar** [comment]
The added fragment is not repacking of another library. I initially thought I need to repack, but I figured out the fragment works as well. Therefore, I added a fragment. I don't think this is something that can be done only in a pom.xml.

If maven-osgi-bundles is a more appropriate location, I can move it there. In that case should I create a plugins folder to store the fragment?

**Comment by berryma4** [comment]
It's a little misleading, the maven-osgi-bundles/repository/pom.xml is using:
https://github.com/reficio/p2-maven-plugin
which takes binaries from maven central, then wraps them into bundles (and you can pass instructions to BND, to change how it is bundled, and if it should bundle depends).

**Comment by jbobnar** [comment]
> which takes binaries from maven central, then wraps them into bundles
If I want to use p2-maven-plugin I have to specify an artifact that exists in the central repository. If it doesn't exist, build fails. For my fragment there is no existing code to wrap. The fragment itself has no code at all. All it has is one manifest file that fixes dependencies of an existing bundle: 
https://github.com/css-iter/cs-studio-thirdparty/tree/master/plugins/org.csstudio.batik.dom.svg.fragment

**Comment by berryma4** [comment]
If all you need to do is add:
Require-Bundle: org.apache.batik.ext.awt;bundle-version="1.7.0"

We can just add that to the instructions for batik:
<instructions>

<Require-Bundle>*;org.apache.batik.ext.awt;bundle-version="1.7.0"</Require-Bundle>
</instructions>

**Comment by jbobnar** [comment]
> We can just add that to the instructions for batik:
We could, but then we need to redefine batik artifacts completely. Right now maven-osgi-bundles pack batik 1.5, which comes in a single package. If we want to do that with batik 1.7, we need to add about 10 batik plugins, because the batik code has been split (there is no batik:batik:1.7). If that is a preferred solution, I'll add those artifacts to the pom.xml.

**Comment by berryma4** [comment]
Yes, if you need all ten, that's preferred.

**Comment by berryma4** [comment]
Although, batik 1.7 is in eclipse orbit, which is first preferred
(Maven-osgi-bundles second, then cs-studio-thirdparty)

**Pull request closed without merging**
