### PR TITLE
Update pom to build against Eclipse Oxygen.

### PR DESCRIPTION
**Pull request by willrogers**
I simply updated the p2 repositories in all the repos to Oxygen and everything seemed to build fine.

I expect @berryma4 will be able to spot if I've missed something.

### CODE REVIEW

**Comment by kasemir** [comment]
Does the resulting product run with Java 9?
If not, are the remaining errors limited to our code accessing API that has been removed?

**Comment by willrogers** [comment]
See https://github.com/ControlSystemStudio/cs-studio/issues/2401

**Comment by willrogers** [comment]
I don't know yet because I haven't tried.

**Comment by willrogers** [comment]
I guess you don't want to merge this until we all agree that all parts work with Oxygen.

**Comment by willrogers** [comment]
@kasemir using Oracle JDK 9.0.4 I added the command-line options `--add-modules ALL-SYSTEM` and it launched just fine. I get this warning:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.emf.ecore.xmi.impl.XMLHandler (file:/scratch/hgs15624/css/org.csstudio.dls.product/repository/target/products/cs-studio/linux/gtk/x86_64/cs-studio/plugins/org.eclipse.emf.ecore.xmi_2.13.0.v20170609-0707.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
WARNING: Please consider reporting this to the maintainers of org.eclipse.emf.ecore.xmi.impl.XMLHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by kasemir** [comment]
> JDK 9.0.4 .. it launched just fine. 

That is terrific!!! Would be great to (at least have to option to) run with Java 9.

**Pull request merged**
