### PR TITLE
KNOBS 1.0.5

### PR DESCRIPTION
**Pull request by claudio-rosati**
KNOBS startup improved from 500-700ms to 15-25ms.

### CODE REVIEW

**Comment by kasemir** [comment]
Any idea what changed in the underlying library, so we have a hint as to what we should avoid?

**Comment by claudio-rosati** [comment]
Yes I now: the library is a complete rework made by myself of the HanSolo's regulator.
My first target was to have the new library working (using a full JavaFX approach, without the need of a redraw method...).
This time I've addressed the startup time, pushing the init method in a different thread, and accumulating in a temporary list events occuring during the initialization.

**Comment by claudio-rosati** [comment]
Source code and test program can be found here: [KNOBS](https://github.com/ESSICS/KNOBS)

**Comment by berryma4** [comment]
"Knobs" looks very nice, but could you maybe do releases to maven central?

**Pull request merged**
